config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "forum_threads#index"

  resources :forum_threads, only: [:show, :new, :create] do
    resources :forum_posts, only: [:create]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forum_post.rb
class ForumPost < ApplicationRecord

    belongs_to :user
    belongs_to :forum_thread, counter_cache: true

    validates :content, presence: true

end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
    belongs_to :user
    has_many :forum_posts

    validates :title, presence: true, length: {maximum: 50}
    validates :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :forum_threads
  has_many :forum_posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController

    before_action :authenticate_user!, only: [:create]

    def create
        @thread = ForumThread.find(params[:forum_thread_id])
        @post = ForumPost.new(resource_param)

        @post.forum_thread = @thread
        @post.user = current_user
        if @post.save 

        redirect_to forum_thread_path(@thread)

        else 
            render 'forum_threads/show'
        end
    end

    private
    def resource_param
        params.require(:forum_post).permit(:content)
    end

end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]
    def index
        @threads = ForumThread.order(id: :desc)
    end

    
    def show
        @thread = ForumThread::find(params[:id])
        @post = ForumPost.new
    end

    def new
        @thread = ForumThread.new
    end

    def create
        @thread = ForumThread.new(resource_param)
        @thread.user = current_user

        if @thread.save
            redirect_to root_path
            flash.alert = "Berhasil Disimpan"
        else
            render 'new'
        end
    end

    private 

    def resource_param
        params.require(:forum_thread). permit(:title, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forum_threads/index.html.erb
<div class="row">
    <div class="col-md-6 offset-md-3">
    <% if user_signed_in?%>
    <%= link_to 'Buat Diskusi', new_forum_thread_path, class: 'btn btn-primary' %>
    <%end%>
    </br>
    </br>
    <% @threads.each do |t| %>
        <div class="thread">
            <h4><%= link_to t.title.titleize, forum_thread_path(t), style: 'text-decoration: none;' %></h4>

            <div class="meta">
                <%= I18n.l( t.created_at.to_date )%> oleh <%= t.user.name %>
            </div>

            <div class="content">
                <%= t.content%>    
            </div>

            <div class='count'>
               <%= t.forum_posts_count%> Obrolan
            </div>

            <div style='clear: both'>
            </div>
        </div>
    <% end %>
        
    </div>
    
 </div>

app/views/forum_threads/new.html.erb
<div class='col-md-6 offset-md-3'>

    <% if @thread.errors.any? %>
        <div class='alert alert-danger alert-dismissible'>
        <% @thread.errors.full_messages.each do |error| %>
            <span> <%= error %> </span></br>
        <% end %>
        </div>
    <%end%>
    <%= form_for @thread, local: true, data: { turbo: false } do |f| %>
        <div class='form-group'>
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class='form-group'>
            <%= f.label :content %>
            <%= f.text_area :content, rows:10, class: 'form-control' %>
        </div>
        <br>
        <div class='form-group'>
            <%= f.submit 'Simpan', class: 'btn btn-primary form-control'%>
        </div>
    
        <% end %>
</div>

app/views/forum_threads/show.html.erb
<div class="row">
    <div class="col-md-6 offset-md-3">
        </br>
        <div class="thread">
            <h4><%= @thread.title.titleize %></h4>

            <div class="meta">
                <%= I18n.l( @thread.created_at.to_date )%> oleh <%= @thread.user.name %>
            </div>

            <div class="content">
                <%= @thread.content%>    
            </div>

        </div>

        <% if @thread.forum_posts.any? %>
            <% @thread.forum_posts.each do |p| %>
                <div class='thread'>

                    <div class="meta">
                        <%= I18n.l( p.created_at.to_date )%> oleh <%= p.user.name %>
                    </div>

                    <div class="content">
                        <%= p.content%>    
                    </div>

                </div>
            <% end %>
        <% else %>
            <div>
            Jadilah yang pertama memberi tanggapan
            </div>
        <% end %>
        <% if user_signed_in?%>
        <% if @post.errors.any? %>
            <div class='alert alert-danger alert-dismissible'>
            <% @post.errors.full_messages.each do |error| %>
                <span> <%= error %> </span></br>
            <% end %>
            </div>
        <%end%>

        <%= form_for [@thread, @post], local: true, data: { turbo: false } do |f| %>
            <div class='form-group'>
                <%= f.label :content %>
                <%= f.text_area :content, rows:10, class: 'form-control' %>
            </div>
            <br>
            <div class='form-group'>
                <%= f.submit 'Simpan', class: 'btn btn-primary form-control'%>
            </div>
            </br>

        <% end %>
        <% end %>
        
    </div>
    
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <%= link_to 'Forum', root_path, class: 'navbar-brand'%>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= user_signed_in? ? current_user.name : 'Halo Guest'%>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if user_signed_in?%>
                <li><%= link_to 'Logout', destroy_user_session_path, data: { "turbo-method": :delete}, class: 'dropdown-item' %></li>
    
                <%else%>
                <li><%= link_to 'Daftar', new_user_registration_path, class: 'dropdown-item'%></li>
                <li><%= link_to 'Login', new_user_session_path, class: 'dropdown-item'%></li>
                <%end%>
            </ul>
            </li>
        </ul>
        <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= render 'layouts/navbar'%>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>